"""Deterministic Airflow 3 DAG generator for the supported v1alpha1 IR subset."""

import argparse
import json
import re
import textwrap
from pathlib import Path
from typing import cast

from croniter import croniter
from jinja2 import Environment, StrictUndefined
from pydantic import JsonValue

from dagwright.adapters.base import (
    AdapterCapabilities,
    ArtifactBundle,
    ArtifactManifest,
    ArtifactMetadata,
    CapabilityViolation,
    GeneratedArtifact,
    LineageMetadata,
    TaskMetadata,
    UnsupportedSemanticsError,
)
from dagwright.compiler.canonical import canonical_bytes, canonical_digest
from dagwright.compiler.ir import DependencyEdge, PipelineIR, PipelineNode

ADAPTER_VERSION = "0.1.0"
TARGET_VERSION = ">=3.0,<4"
CAPABILITY_PATH = "adapters/airflow/capabilities-v1alpha1.json"
_SCHEDULE_PRESETS = {"@once", "@hourly", "@daily", "@weekly", "@monthly", "@yearly"}
_SUPPORTED_NODE_KINDS = {"source", "asset", "transformation", "quality", "anomaly"}
_SUPPORTED_EDGE_KINDS = {"reads", "depends_on", "transforms", "validates", "observes"}

_AIRFLOW_TEMPLATE = '''"""Generated by DAGwright Airflow 3 adapter; do not edit.

This is a fail-closed orchestration scaffold. Task bodies deliberately fail until
workload and quality implementations are bound by later adapters.
"""

from __future__ import annotations

from datetime import UTC, datetime

from airflow.sdk import dag as airflow_dag
from airflow.sdk import task

DAGWRIGHT_IR_DIGEST = {{ ir_digest | tojson }}
DAGWRIGHT_CONTRACT_DIGEST = {{ contract_digest | tojson }}


@airflow_dag(
    dag_id={{ dag_id | tojson }},
    schedule={{ schedule_literal }},
    start_date=datetime(1970, 1, 1, tzinfo=UTC),
    catchup=False,
    tags=["dagwright", "generated", "v1alpha1"],
    doc_md="Generated from a DAGwright v1alpha1 canonical IR.",
)
def build_dag() -> None:
{% for item in tasks %}
    @task(task_id={{ item.task_id | tojson }}, retries={{ item.retries }})
    def {{ item.function }}() -> None:
        """Fail-closed {{ item.kind }} scaffold."""
        raise RuntimeError(
{% for line in item.reason_lines %}            {{ line | tojson }}
{% endfor %}        )

    {{ item.variable }} = {{ item.function }}()

{% endfor %}
    # Canonical dependencies from the DAGwright IR.
{% for item in dependencies %}
    {{ item.upstream }} >> {{ item.downstream }}
{% endfor %}


dag = build_dag()
'''


class Airflow3Adapter:
    """Generate Airflow 3 Task SDK source without importing or invoking Airflow."""

    def capabilities(self) -> AdapterCapabilities:
        return AdapterCapabilities(
            api_version="dagwright.io/adapter-capabilities/v1alpha1",
            name="airflow3",
            adapter_version=ADAPTER_VERSION,
            target="apache-airflow",
            target_version=TARGET_VERSION,
            contract_versions=("dagwright.io/v1alpha1",),
            ir_versions=("dagwright.ir/v1alpha1",),
            generation_only=True,
            batch=True,
            streaming=False,
            cdc="delegated_to_source",
            checkpointing=False,
            watermarks="delegated_to_workload",
            exactly_once_scope="none",
            schema_evolution=False,
            rollback=False,
            dry_run=True,
            lineage=True,
            cost_visibility=False,
            schedules=("manual", "cron", "preset"),
            quality_gates="structural_fail_closed",
            operational_contracts="quality_fail_closed_others_delegated",
        )

    def validate(self, ir: PipelineIR) -> tuple[CapabilityViolation, ...]:
        violations: list[CapabilityViolation] = []
        if ir.contract_api_version not in self.capabilities().contract_versions:
            violations.append(
                _violation(
                    "unsupported_contract_version",
                    "/contractApiVersion",
                    f"supported versions: {', '.join(self.capabilities().contract_versions)}",
                )
            )
        if ir.ir_version not in self.capabilities().ir_versions:
            violations.append(
                _violation(
                    "unsupported_ir_version",
                    "/irVersion",
                    f"supported versions: {', '.join(self.capabilities().ir_versions)}",
                )
            )
        if ir.execution.orchestrator != "airflow":
            violations.append(
                _violation(
                    "unsupported_orchestrator",
                    "/execution/orchestrator",
                    "expected 'airflow'",
                )
            )
        if not _supported_schedule(ir.execution.schedule):
            violations.append(
                _violation(
                    "unsupported_schedule",
                    "/execution/schedule",
                    "expected null, a five-field cron expression, or a standard Airflow preset",
                )
            )
        node_ids = {node.stable_id for node in ir.nodes}
        generated_task_ids: dict[str, list[str]] = {}
        for index, node in enumerate(ir.nodes):
            path = f"/nodes/{index}"
            if node.kind not in _SUPPORTED_NODE_KINDS:
                violations.append(
                    _violation(
                        "unsupported_node_kind", f"{path}/kind", f"unsupported {node.kind!r}"
                    )
                )
            if node.failure_policy != {"action": "fail"}:
                violations.append(
                    _violation(
                        "unsupported_failure_policy",
                        f"{path}/failurePolicy",
                        "only fail-closed tasks are supported",
                    )
                )
            retries = node.retry_policy.get("maxAttempts")
            if (
                not isinstance(retries, int)
                or isinstance(retries, bool)
                or retries < 1
                or set(node.retry_policy) != {"maxAttempts"}
            ):
                violations.append(
                    _violation(
                        "unsupported_retry_policy",
                        f"{path}/retryPolicy",
                        "expected only integer maxAttempts >= 1",
                    )
                )
            if node.kind == "source" and node.execution_semantics.get("captureMode") == "stream":
                violations.append(
                    _violation(
                        "streaming_not_supported",
                        f"{path}/executionSemantics/captureMode",
                        "Airflow 3 adapter supports batch and delegated CDC sources only",
                    )
                )
            generated_task_ids.setdefault(_task_id(node), []).append(node.stable_id)
        for task_id, stable_ids in sorted(generated_task_ids.items()):
            if len(stable_ids) > 1:
                violations.append(
                    _violation(
                        "task_id_collision",
                        "/nodes",
                        f"generated task ID {task_id!r} is shared by {', '.join(stable_ids)}",
                    )
                )
        for index, edge in enumerate(ir.edges):
            if edge.kind not in _SUPPORTED_EDGE_KINDS:
                violations.append(
                    _violation(
                        "unsupported_edge_kind",
                        f"/edges/{index}/kind",
                        f"unsupported {edge.kind!r}",
                    )
                )
            if edge.source not in node_ids or edge.target not in node_ids:
                violations.append(
                    _violation(
                        "unresolved_edge",
                        f"/edges/{index}",
                        "edge endpoints must reference generated nodes",
                    )
                )
        return tuple(sorted(violations, key=lambda item: (item.path, item.code, item.message)))

    def generate(self, ir: PipelineIR) -> ArtifactBundle:
        violations = self.validate(ir)
        if violations:
            raise UnsupportedSemanticsError(self.capabilities().name, violations)
        ir_digest = canonical_digest(ir)
        nodes = tuple(sorted(ir.nodes, key=lambda node: node.stable_id))
        edges = tuple(
            sorted(ir.edges, key=lambda edge: (edge.source, edge.target, edge.kind, edge.stable_id))
        )
        task_ids = {node.stable_id: _task_id(node) for node in nodes}
        artifact = GeneratedArtifact(
            path=f"dags/{_dag_id(ir)}.py",
            media_type="text/x-python",
            content=_render_dag(ir, ir_digest, task_ids, nodes, edges).encode(),
        )
        lineage = tuple(
            LineageMetadata(
                edge_id=edge.stable_id,
                edge_kind=edge.kind,
                upstream_stable_id=edge.source,
                downstream_stable_id=edge.target,
                upstream_task_id=task_ids[edge.source],
                downstream_task_id=task_ids[edge.target],
            )
            for edge in edges
        )
        manifest = ArtifactManifest(
            api_version="dagwright.io/artifact-manifest/v1alpha1",
            adapter=self.capabilities().name,
            adapter_version=ADAPTER_VERSION,
            target_version=TARGET_VERSION,
            generation_mode="fail_closed_scaffold",
            input_ir_digest=ir_digest,
            contract_digest=ir.contract_digest,
            delegated_operational_contracts=ir.operational_contracts,
            artifacts=(
                ArtifactMetadata(
                    path=artifact.path,
                    media_type=artifact.media_type,
                    role="orchestrator_dag",
                    sha256=artifact.sha256,
                    size=len(artifact.content),
                ),
            ),
            tasks=tuple(_task_metadata(node, task_ids[node.stable_id]) for node in nodes),
            lineage=lineage,
        )
        return ArtifactBundle(
            artifact=artifact,
            manifest=manifest,
            manifest_bytes=canonical_bytes(manifest),
        )


def capability_bytes() -> bytes:
    """Return the canonical published Airflow capability document."""
    return (
        json.dumps(
            Airflow3Adapter().capabilities().model_dump(mode="json", by_alias=True),
            indent=2,
            sort_keys=True,
        ).encode()
        + b"\n"
    )


def main() -> int:
    """Write or verify the published capability document."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=Path(CAPABILITY_PATH))
    args = parser.parse_args()
    expected = capability_bytes()
    if args.check:
        if not args.output.exists() or args.output.read_bytes() != expected:
            parser.error(f"{args.output} is stale; regenerate it with this module")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(expected)
    return 0


def _render_dag(
    ir: PipelineIR,
    ir_digest: str,
    task_ids: dict[str, str],
    nodes: tuple[PipelineNode, ...],
    edges: tuple[DependencyEdge, ...],
) -> str:
    variable_names: dict[str, str] = {}
    tasks: list[dict[str, object]] = []
    for index, node in enumerate(nodes):
        function = f"task_{index:03d}"
        variable = f"node_{index:03d}"
        variable_names[node.stable_id] = variable
        tasks.append(
            {
                "function": function,
                "kind": node.kind,
                "reason_lines": _reason_lines(_failure_message(node)),
                "retries": cast(int, node.retry_policy["maxAttempts"]) - 1,
                "task_id": task_ids[node.stable_id],
                "variable": variable,
            }
        )
    dependencies = [
        {"upstream": variable_names[edge.source], "downstream": variable_names[edge.target]}
        for edge in edges
    ]
    environment = Environment(
        autoescape=False,
        keep_trailing_newline=True,
        trim_blocks=True,
        undefined=StrictUndefined,
    )
    return environment.from_string(_AIRFLOW_TEMPLATE).render(
        contract_digest=ir.contract_digest,
        dag_id=_dag_id(ir),
        dependencies=dependencies,
        ir_digest=ir_digest,
        schedule_literal=_python_literal(ir.execution.schedule),
        tasks=tasks,
    )


def _failure_message(node: PipelineNode) -> str:
    if node.kind == "quality":
        prefix = "Quality gate"
    elif node.kind == "anomaly":
        prefix = "Anomaly check"
    else:
        prefix = "Workload"
    return f"{prefix} {node.stable_id} has no bound execution implementation"


def _reason_lines(value: str) -> list[str]:
    chunks = textwrap.wrap(value, width=68, break_long_words=False, break_on_hyphens=False)
    return [chunk + (" " if index < len(chunks) - 1 else "") for index, chunk in enumerate(chunks)]


def _data_product_name(ir: PipelineIR) -> str:
    return ir.data_product_id.split(":", maxsplit=3)[2]


def _dag_id(ir: PipelineIR) -> str:
    return f"dagwright__{_python_name(_data_product_name(ir))}"


def _task_id(node: PipelineNode) -> str:
    return f"{_python_name(node.kind)}__{_python_name(node.name)}"


def _python_name(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", value)


def _supported_schedule(schedule: str | None) -> bool:
    if schedule is None or schedule in _SCHEDULE_PRESETS:
        return True
    return len(schedule.split()) == 5 and croniter.is_valid(schedule)


def _python_literal(value: JsonValue) -> str:
    if value is None:
        return "None"
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def _task_metadata(node: PipelineNode, task_id: str) -> TaskMetadata:
    severity_value = node.execution_semantics.get("severity")
    severity = severity_value if isinstance(severity_value, str) else None
    return TaskMetadata(
        stable_id=node.stable_id,
        task_id=task_id,
        kind=node.kind,
        source_contract_location=node.source_contract_location,
        retries=cast(int, node.retry_policy["maxAttempts"]) - 1,
        quality_gate=node.kind == "quality",
        severity=severity,
    )


def _violation(code: str, path: str, message: str) -> CapabilityViolation:
    return CapabilityViolation(code=code, path=path, message=message)


if __name__ == "__main__":
    raise SystemExit(main())
