"""Deterministic Spark/Iceberg workload artifact generator."""

import hashlib
import json
import re
from dataclasses import dataclass

from jinja2 import Environment, StrictUndefined
from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel

from dagwright.compiler.canonical import canonical_bytes, canonical_digest
from dagwright.compiler.ir import PipelineIR

ADAPTER_VERSION = "0.1.0"

_SPARK_TEMPLATE = '''"""Generated by DAGwright; do not edit."""

from pyspark.sql import SparkSession

DAGWRIGHT_IR_DIGEST = {{ ir_digest | tojson }}
DAGWRIGHT_CONTRACT_DIGEST = {{ contract_digest | tojson }}
TRANSFORMATION_ID = {{ transformation_id | tojson }}
OUTPUT_TABLE = {{ output_table | tojson }}
SQL = (
{% for line in sql_lines %}    {{ line | tojson }}
{% endfor %})


def main() -> None:
    spark = SparkSession.builder.appName({{ application_name | tojson }}).getOrCreate()
    try:
        spark.sql(SQL).writeTo(OUTPUT_TABLE).createOrReplace()
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
'''


class SparkModel(BaseModel):
    model_config = ConfigDict(
        alias_generator=to_camel,
        extra="forbid",
        frozen=True,
        strict=True,
        validate_by_alias=True,
        validate_by_name=True,
    )


class SparkArtifactMetadata(SparkModel):
    path: str
    media_type: str
    role: str
    sha256: str
    size: int


class SparkManifest(SparkModel):
    api_version: str
    adapter: str
    adapter_version: str
    input_ir_digest: str
    contract_digest: str
    artifacts: tuple[SparkArtifactMetadata, ...]


@dataclass(frozen=True)
class SparkArtifact:
    path: str
    media_type: str
    role: str
    content: bytes

    @property
    def sha256(self) -> str:
        return hashlib.sha256(self.content).hexdigest()


@dataclass(frozen=True)
class SparkBundle:
    artifacts: tuple[SparkArtifact, ...]
    manifest: SparkManifest
    manifest_bytes: bytes


class SparkIcebergAdapter:
    """Generate PySpark SQL jobs and deterministic Iceberg table metadata."""

    def generate(self, ir: PipelineIR, sql_by_transformation: dict[str, str]) -> SparkBundle:
        if ir.execution.transform_engine != "spark":
            raise ValueError("Spark adapter requires execution.transformEngine 'spark'")
        ir_digest = canonical_digest(ir)
        environment = Environment(
            autoescape=False,
            keep_trailing_newline=True,
            undefined=StrictUndefined,
        )
        template = environment.from_string(_SPARK_TEMPLATE)
        artifacts: list[SparkArtifact] = []
        output_by_transformation = {
            node.name: next(
                target.name
                for target in ir.nodes
                if target.stable_id in node.outputs and target.kind == "asset"
            )
            for node in ir.nodes
            if node.kind == "transformation"
        }
        for transformation_id, sql in sorted(sql_by_transformation.items()):
            output = output_by_transformation[transformation_id]
            source = template.render(
                application_name=f"dagwright-{transformation_id}",
                contract_digest=ir.contract_digest,
                ir_digest=ir_digest,
                output_table=output,
                sql_lines=sql.splitlines(keepends=True),
                transformation_id=transformation_id,
            ).encode()
            artifacts.append(
                SparkArtifact(
                    path=f"spark/{_safe_name(transformation_id)}.py",
                    media_type="text/x-python",
                    role="spark_job",
                    content=source,
                )
            )
        tables = {
            "apiVersion": "dagwright.io/iceberg-tables/v1alpha1",
            "catalog": ir.execution.target_catalog,
            "tables": [
                {
                    "name": node.name,
                    "mode": node.execution_semantics.get("mode"),
                    "primaryKey": node.execution_semantics.get("primaryKey", []),
                }
                for node in sorted(ir.nodes, key=lambda item: item.stable_id)
                if node.kind == "asset" and node.execution_semantics.get("type") == "iceberg_table"
            ],
        }
        artifacts.append(
            SparkArtifact(
                path="iceberg/tables.json",
                media_type="application/json",
                role="iceberg_metadata",
                content=(json.dumps(tables, indent=2, sort_keys=True) + "\n").encode(),
            )
        )
        ordered = tuple(sorted(artifacts, key=lambda item: item.path))
        manifest = SparkManifest(
            api_version="dagwright.io/spark-artifact-manifest/v1alpha1",
            adapter="spark-iceberg",
            adapter_version=ADAPTER_VERSION,
            input_ir_digest=ir_digest,
            contract_digest=ir.contract_digest,
            artifacts=tuple(
                SparkArtifactMetadata(
                    path=item.path,
                    media_type=item.media_type,
                    role=item.role,
                    sha256=item.sha256,
                    size=len(item.content),
                )
                for item in ordered
            ),
        )
        return SparkBundle(ordered, manifest, canonical_bytes(manifest))


def _safe_name(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", value)
