"""Generated by DAGwright; do not edit."""

from pyspark.sql import SparkSession

DAGWRIGHT_IR_DIGEST = "28e2d489938543f50d24d0cba3ae2598e49131a5710017b2bc20a4fd3cfd49d1"
DAGWRIGHT_CONTRACT_DIGEST = "30cc3263dbce553334448c84e32075608673248189bf9405968a7d95d7a858b3"
TRANSFORMATION_ID = "build-customer-engagement"
OUTPUT_TABLE = "customer_engagement"
SQL = (
    "/* Reference transformation owned by the example project. */\n"
    "SELECT\n"
    "  customers.customer_id,\n"
    "  customers.email,\n"
    "  COUNT(events.event_id) AS event_count,\n"
    "  MAX(events.occurred_at) AS last_event_at\n"
    "FROM raw_customers AS customers\n"
    "LEFT JOIN raw_customer_events AS events\n"
    "  ON customers.customer_id = events.customer_id\n"
    "GROUP BY\n"
    "  customers.customer_id,\n"
    "  customers.email"
)


def main() -> None:
    spark = SparkSession.builder.appName("dagwright-build-customer-engagement").getOrCreate()
    try:
        spark.sql(SQL).writeTo(OUTPUT_TABLE).createOrReplace()
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
