"""Generated by DAGwright; do not edit."""

from pyspark.sql import SparkSession

DAGWRIGHT_IR_DIGEST = "bced29a5bd47075f1e4de44034874590e797775584e1d0ad4d03bfe5c4292658"
DAGWRIGHT_CONTRACT_DIGEST = "fac7eccc9d0e3f54f6265c3e66cdae114b85a7d064069daa02826353f8a62a6b"
TRANSFORMATION_ID = "build-customer-engagement"
OUTPUT_TABLE = "customer_engagement"
SQL = (
    "/* Reference transformation owned by the example project. */\n"
    "SELECT\n"
    "  customers.customer_id,\n"
    "  customers.email,\n"
    "  COUNT(events.event_id) AS event_count,\n"
    "  MAX(events.occurred_at) AS last_event_at\n"
    "FROM raw_customers AS customers\n"
    "LEFT JOIN raw_customer_events AS events\n"
    "  ON customers.customer_id = events.customer_id\n"
    "GROUP BY\n"
    "  customers.customer_id,\n"
    "  customers.email"
)


def main() -> None:
    spark = SparkSession.builder.appName("dagwright-build-customer-engagement").getOrCreate()
    try:
        spark.sql(SQL).writeTo(OUTPUT_TABLE).createOrReplace()
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
