"""Generated by DAGwright Airflow 3 adapter; do not edit.

This is a fail-closed orchestration scaffold. Task bodies deliberately fail until
workload and quality implementations are bound by later adapters.
"""

from __future__ import annotations

from datetime import UTC, datetime

from airflow.sdk import dag as airflow_dag
from airflow.sdk import task

DAGWRIGHT_IR_DIGEST = "578d9cc49d2dc38a97748246d880b182b06824ec332edfe8f7ae0c573e8541bb"
DAGWRIGHT_CONTRACT_DIGEST = "d1bec0c0f388b00c7c14acee77d67251e2b57dde62aca44c63876d2afb407aa4"


@airflow_dag(
    dag_id="dagwright__customer_360",
    schedule="*/5 * * * *",
    start_date=datetime(1970, 1, 1, tzinfo=UTC),
    catchup=False,
    tags=["dagwright", "generated", "v1alpha1"],
    doc_md="Generated from a DAGwright v1alpha1 canonical IR.",
)
def build_dag() -> None:
    @task(task_id="anomaly__customer_volume_change", retries=0)
    def task_000() -> None:
        """Fail-closed anomaly scaffold."""
        raise RuntimeError(
            "Anomaly check "
            "urn:dagwright:customer-360:anomaly:customer-volume-change has no "
            "bound execution implementation"
        )

    node_000 = task_000()

    @task(task_id="asset__bronze_customers", retries=0)
    def task_001() -> None:
        """Fail-closed asset scaffold."""
        raise RuntimeError(
            "Workload urn:dagwright:customer-360:asset:bronze_customers has no "
            "bound execution implementation"
        )

    node_001 = task_001()

    @task(task_id="asset__silver_customers", retries=0)
    def task_002() -> None:
        """Fail-closed asset scaffold."""
        raise RuntimeError(
            "Workload urn:dagwright:customer-360:asset:silver_customers has no "
            "bound execution implementation"
        )

    node_002 = task_002()

    @task(task_id="quality__customer_id_required", retries=0)
    def task_003() -> None:
        """Fail-closed quality scaffold."""
        raise RuntimeError(
            "Quality gate urn:dagwright:customer-360:quality:customer-id-required "
            "has no bound execution implementation"
        )

    node_003 = task_003()

    @task(task_id="source__customers_db", retries=0)
    def task_004() -> None:
        """Fail-closed source scaffold."""
        raise RuntimeError(
            "Workload urn:dagwright:customer-360:source:customers-db has no bound "
            "execution implementation"
        )

    node_004 = task_004()

    @task(task_id="transformation__build_customer_profile", retries=0)
    def task_005() -> None:
        """Fail-closed transformation scaffold."""
        raise RuntimeError(
            "Workload "
            "urn:dagwright:customer-360:transformation:build-customer-profile has "
            "no bound execution implementation"
        )

    node_005 = task_005()

    # Canonical dependencies from the DAGwright IR.
    node_001 >> node_005
    node_002 >> node_000
    node_002 >> node_003
    node_004 >> node_001
    node_005 >> node_002


dag = build_dag()
